pipeline {
  agent any

  environment {
    DOCKERHUB_CREDENTIALS = 'dockerhub-creds'
    IMAGE_NAME = "ahmedmohamed1242001/backend"
    KUBE_NAMESPACE = "default"
    GIT_REPO = "https://github.com/ahmedmohamedrafat00-cpu/devops-project.git"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        sh 'echo "No build step yet (nginx test image)"'
      }
    }

    stage('Docker Build & Push') {
      steps {
        script {
          withCredentials([usernamePassword(
            credentialsId: env.DOCKERHUB_CREDENTIALS,
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
          )]) {
            sh '''
              echo "Building Docker image..."
              cd apps/backend
              docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} .
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push ${IMAGE_NAME}:${BUILD_NUMBER}
              cd ../..
            '''
          }
        }
      }
    }

    stage('Deploy to EKS (Helm)') {
      steps {
        sh '''
          echo "Cloning full repo for Helm..."
          rm -rf helm-workspace
          git clone ${GIT_REPO} helm-workspace

          echo "========== DEBUG =========="
          pwd
          ls -la
          ls -la helm-workspace
          ls -la helm-workspace/k8s || true
          ls -la helm-workspace/k8s/charts || true
          ls -la helm-workspace/k8s/charts/backend || true
          echo "==========================="

          cd helm-workspace/k8s/charts/backend

          echo "Deploying with Helm..."
          helm upgrade --install backend . \
            --set image.repository=${IMAGE_NAME} \
            --set image.tag=${BUILD_NUMBER} \
            --namespace ${KUBE_NAMESPACE}
        '''
      }
    }
  }

  post {
    success {
      echo "✅ CI/CD Pipeline Finished Successfully"
    }
    failure {
      echo "❌ CI/CD Pipeline Failed"
    }
  }
}
